- name: Copy API Dockerfile
  copy:
    src: ../../docker/api.Dockerfile
    dest: ~/api.Dockerfile

- name: Copy API code and model
  copy:
    src:
      - ../../api/app.py
      - ../../models/model.pkl
      - ../../requirements.txt
    dest: ~/app/

- name: Build API image
  command: docker build -t titanic-api -f ~/api.Dockerfile ~/app

- name: Run API container
  docker_container:
    name: titanic_api
    image: titanic-api
    state: started
    restart_policy: always
    ports:
      - "8000:8000"
    command: uvicorn api.app:app --host 0.0.0.0 --port 8000